# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatSystem_pb2 as chatSystem__pb2


class ChatServiceStub(object):
    """Type of communication
    rpc convert(ConvertCurrencyRequest) returns(ConvertCurrencyResponse); //type : unary model
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.chatStream = channel.stream_stream(
                '/ChatService/chatStream',
                request_serializer=chatSystem__pb2.requestMsg.SerializeToString,
                response_deserializer=chatSystem__pb2.response.FromString,
                )


class ChatServiceServicer(object):
    """Type of communication
    rpc convert(ConvertCurrencyRequest) returns(ConvertCurrencyResponse); //type : unary model
    """

    def chatStream(self, request_iterator, context):
        """rpc convertStreamServer(ConvertCurrencyRequest) returns(stream ConvertCurrencyResponse); //type : Server Streaming model

        rpc convertStreamClient(stream ConvertCurrencyRequest) returns(ConvertCurrencyResponse); // type : Client Streaming model

        type : Bi-directional Streaming model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'chatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.chatStream,
                    request_deserializer=chatSystem__pb2.requestMsg.FromString,
                    response_serializer=chatSystem__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Type of communication
    rpc convert(ConvertCurrencyRequest) returns(ConvertCurrencyResponse); //type : unary model
    """

    @staticmethod
    def chatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ChatService/chatStream',
            chatSystem__pb2.requestMsg.SerializeToString,
            chatSystem__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
