# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatSystem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63hatSystem.proto\"/\n\nrequestMsg\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\t\"%\n\x08response\x12\x19\n\x11responseToRequest\x18\x01 \x01(\t\"(\n\x0blistAccount\x12\x19\n\x07\x61\x63\x63ount\x18\x01 \x03(\x0b\x32\x08.Account\"*\n\x12listAccountRequest\x12\x14\n\x0ctotalAccount\x18\x01 \x01(\x03\"C\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x32\x37\n\x0b\x43hatService\x12(\n\nchatStream\x12\x0b.requestMsg\x1a\t.response(\x01\x30\x01\x42\x12\n\x10\x63om.Oussez.stubsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatSystem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020com.Oussez.stubs'
  _REQUESTMSG._serialized_start=20
  _REQUESTMSG._serialized_end=67
  _RESPONSE._serialized_start=69
  _RESPONSE._serialized_end=106
  _LISTACCOUNT._serialized_start=108
  _LISTACCOUNT._serialized_end=148
  _LISTACCOUNTREQUEST._serialized_start=150
  _LISTACCOUNTREQUEST._serialized_end=192
  _ACCOUNT._serialized_start=194
  _ACCOUNT._serialized_end=261
  _CHATSERVICE._serialized_start=263
  _CHATSERVICE._serialized_end=318
# @@protoc_insertion_point(module_scope)
